# Generated by Django 3.2.25 on 2024-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241218_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transaction',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
