# Generated by Django 3.2.25 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
