# Generated by Django 3.2.25 on 2024-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_sales_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
