# Generated by Django 3.2.25 on 2024-12-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20241219_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
